
# reference genome
#reference: /n/fs/ragr-data/datasets/ref-genomes/GRCh37_NCBI/GRCh37.p13.fa 
#reference: /n/fs/ragr-research/users/bjarnold/SomaticVarCall/resources/ref_genomes/hg19/Homo_sapiens_assembly19.fasta
reference: /n/fs/ragr-research/users/bjarnold/SomaticVarCall/resources/ref_genomes/hg19/hs37d5.fa

samples: samples_files/samples_Gundem.txt

autosomes_to_genotype: 22
genotype_sexchroms: True

strelka2:
    cores: 10

mutect2:
    # note, all supplementary database VCF files must be indexed, with .idx prefix
    pon: resources/panel_of_normals/hg19/Mutect2-WGS-panel-b37.vcf.gz
    germline_resource: resources/germline_resource/hg19/af-only-gnomad.raw.sites.vcf.gz
    common_alleles: resources/common_alleles/hg19/small_exac_common_3.vcf.gz

